apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: yuragranovsky/probes-gateway
        resources:
          limits:
            memory: "300Mi"
            cpu: "250m"
        env:
        
        - name: CONFIG_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: probes-microservices-config-map
              key:  configServerHost 
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: probes-microservices-config-map
              key: timeZone                   
        ports:
        - containerPort: 9292

---  
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: LoadBalancer 
  ports:
  - port: 9292
    targetPort: 9292
      
